name = "restaurant-api"
main = "worker/src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "restaurant-db"
database_id = "c86793b3-81ef-4610-b447-06647066884e"

[[r2_buckets]]
binding = "RESTAURANT_IMAGES"
bucket_name = "restaurant-images"
